//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.9.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from /Users/rchdeveloper/Documents/GitHub/api-query-language/raql-dotnet/RAQL.NET/Grammar/RAQL.g4 by ANTLR 4.9.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using System;
using System.IO;
using System.Text;
using System.Diagnostics;
using System.Collections.Generic;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.9.2")]
[System.CLSCompliant(false)]
public partial class RAQLParser : Parser {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		T__0=1, T__1=2, T__2=3, T__3=4, T__4=5, T__5=6, IN=7, BASE_OPERATOR=8, 
		STRING_OPERATOR=9, NUMBER_OPERATOR=10, CONJUNCTIONS=11, NUMBER=12, WORD=13, 
		STRING=14, BOOLEAN=15, NULL=16, WS=17;
	public const int
		RULE_clause = 0, RULE_conjunction = 1, RULE_operation = 2, RULE_string_array_operation = 3, 
		RULE_number_array_operation = 4, RULE_bool_array_operation = 5, RULE_array_operator = 6, 
		RULE_string_operation = 7, RULE_string_operator = 8, RULE_number_operation = 9, 
		RULE_number_operator = 10, RULE_bool_operation = 11, RULE_bool_operator = 12, 
		RULE_field = 13, RULE_nullstring = 14, RULE_string = 15, RULE_string_array = 16, 
		RULE_number = 17, RULE_number_array = 18, RULE_bool = 19, RULE_bool_array = 20;
	public static readonly string[] ruleNames = {
		"clause", "conjunction", "operation", "string_array_operation", "number_array_operation", 
		"bool_array_operation", "array_operator", "string_operation", "string_operator", 
		"number_operation", "number_operator", "bool_operation", "bool_operator", 
		"field", "nullstring", "string", "string_array", "number", "number_array", 
		"bool", "bool_array"
	};

	private static readonly string[] _LiteralNames = {
		null, "'('", "' '", "')'", "'['", "','", "']'", null, null, null, null, 
		null, null, null, null, null, "'null'"
	};
	private static readonly string[] _SymbolicNames = {
		null, null, null, null, null, null, null, "IN", "BASE_OPERATOR", "STRING_OPERATOR", 
		"NUMBER_OPERATOR", "CONJUNCTIONS", "NUMBER", "WORD", "STRING", "BOOLEAN", 
		"NULL", "WS"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "RAQL.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string SerializedAtn { get { return new string(_serializedATN); } }

	static RAQLParser() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}

		public RAQLParser(ITokenStream input) : this(input, Console.Out, Console.Error) { }

		public RAQLParser(ITokenStream input, TextWriter output, TextWriter errorOutput)
		: base(input, output, errorOutput)
	{
		Interpreter = new ParserATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	public partial class ClauseContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ClauseContext[] clause() {
			return GetRuleContexts<ClauseContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public ClauseContext clause(int i) {
			return GetRuleContext<ClauseContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public OperationContext operation() {
			return GetRuleContext<OperationContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ConjunctionContext conjunction() {
			return GetRuleContext<ConjunctionContext>(0);
		}
		public ClauseContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_clause; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IRAQLVisitor<TResult> typedVisitor = visitor as IRAQLVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitClause(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ClauseContext clause() {
		return clause(0);
	}

	private ClauseContext clause(int _p) {
		ParserRuleContext _parentctx = Context;
		int _parentState = State;
		ClauseContext _localctx = new ClauseContext(Context, _parentState);
		ClauseContext _prevctx = _localctx;
		int _startState = 0;
		EnterRecursionRule(_localctx, 0, RULE_clause, _p);
		int _la;
		try {
			int _alt;
			EnterOuterAlt(_localctx, 1);
			{
			State = 54;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,2,Context) ) {
			case 1:
				{
				}
				break;
			case 2:
				{
				State = 43;
				Match(T__0);
				State = 45;
				ErrorHandler.Sync(this);
				switch ( Interpreter.AdaptivePredict(TokenStream,0,Context) ) {
				case 1:
					{
					State = 44;
					Match(T__1);
					}
					break;
				}
				State = 47;
				clause(0);
				State = 49;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				if (_la==T__1) {
					{
					State = 48;
					Match(T__1);
					}
				}

				State = 51;
				Match(T__2);
				}
				break;
			case 3:
				{
				State = 53;
				operation();
				}
				break;
			}
			Context.Stop = TokenStream.LT(-1);
			State = 62;
			ErrorHandler.Sync(this);
			_alt = Interpreter.AdaptivePredict(TokenStream,3,Context);
			while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.INVALID_ALT_NUMBER ) {
				if ( _alt==1 ) {
					if ( ParseListeners!=null )
						TriggerExitRuleEvent();
					_prevctx = _localctx;
					{
					{
					_localctx = new ClauseContext(_parentctx, _parentState);
					PushNewRecursionContext(_localctx, _startState, RULE_clause);
					State = 56;
					if (!(Precpred(Context, 2))) throw new FailedPredicateException(this, "Precpred(Context, 2)");
					State = 57;
					conjunction();
					State = 58;
					clause(3);
					}
					} 
				}
				State = 64;
				ErrorHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(TokenStream,3,Context);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			UnrollRecursionContexts(_parentctx);
		}
		return _localctx;
	}

	public partial class ConjunctionContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode CONJUNCTIONS() { return GetToken(RAQLParser.CONJUNCTIONS, 0); }
		public ConjunctionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_conjunction; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IRAQLVisitor<TResult> typedVisitor = visitor as IRAQLVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitConjunction(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ConjunctionContext conjunction() {
		ConjunctionContext _localctx = new ConjunctionContext(Context, State);
		EnterRule(_localctx, 2, RULE_conjunction);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 65;
			Match(CONJUNCTIONS);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class OperationContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public Bool_array_operationContext bool_array_operation() {
			return GetRuleContext<Bool_array_operationContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Number_array_operationContext number_array_operation() {
			return GetRuleContext<Number_array_operationContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public String_array_operationContext string_array_operation() {
			return GetRuleContext<String_array_operationContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Bool_operationContext bool_operation() {
			return GetRuleContext<Bool_operationContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Number_operationContext number_operation() {
			return GetRuleContext<Number_operationContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public String_operationContext string_operation() {
			return GetRuleContext<String_operationContext>(0);
		}
		public OperationContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_operation; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IRAQLVisitor<TResult> typedVisitor = visitor as IRAQLVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitOperation(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public OperationContext operation() {
		OperationContext _localctx = new OperationContext(Context, State);
		EnterRule(_localctx, 4, RULE_operation);
		try {
			State = 73;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,4,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 67;
				bool_array_operation();
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 68;
				number_array_operation();
				}
				break;
			case 3:
				EnterOuterAlt(_localctx, 3);
				{
				State = 69;
				string_array_operation();
				}
				break;
			case 4:
				EnterOuterAlt(_localctx, 4);
				{
				State = 70;
				bool_operation();
				}
				break;
			case 5:
				EnterOuterAlt(_localctx, 5);
				{
				State = 71;
				number_operation();
				}
				break;
			case 6:
				EnterOuterAlt(_localctx, 6);
				{
				State = 72;
				string_operation();
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class String_array_operationContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public FieldContext field() {
			return GetRuleContext<FieldContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Array_operatorContext array_operator() {
			return GetRuleContext<Array_operatorContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public String_arrayContext string_array() {
			return GetRuleContext<String_arrayContext>(0);
		}
		public String_array_operationContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_string_array_operation; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IRAQLVisitor<TResult> typedVisitor = visitor as IRAQLVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitString_array_operation(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public String_array_operationContext string_array_operation() {
		String_array_operationContext _localctx = new String_array_operationContext(Context, State);
		EnterRule(_localctx, 6, RULE_string_array_operation);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 75;
			field();
			State = 76;
			array_operator();
			State = 77;
			string_array();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Number_array_operationContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public FieldContext field() {
			return GetRuleContext<FieldContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Array_operatorContext array_operator() {
			return GetRuleContext<Array_operatorContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Number_arrayContext number_array() {
			return GetRuleContext<Number_arrayContext>(0);
		}
		public Number_array_operationContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_number_array_operation; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IRAQLVisitor<TResult> typedVisitor = visitor as IRAQLVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitNumber_array_operation(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Number_array_operationContext number_array_operation() {
		Number_array_operationContext _localctx = new Number_array_operationContext(Context, State);
		EnterRule(_localctx, 8, RULE_number_array_operation);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 79;
			field();
			State = 80;
			array_operator();
			State = 81;
			number_array();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Bool_array_operationContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public FieldContext field() {
			return GetRuleContext<FieldContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Array_operatorContext array_operator() {
			return GetRuleContext<Array_operatorContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Bool_arrayContext bool_array() {
			return GetRuleContext<Bool_arrayContext>(0);
		}
		public Bool_array_operationContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_bool_array_operation; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IRAQLVisitor<TResult> typedVisitor = visitor as IRAQLVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitBool_array_operation(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Bool_array_operationContext bool_array_operation() {
		Bool_array_operationContext _localctx = new Bool_array_operationContext(Context, State);
		EnterRule(_localctx, 10, RULE_bool_array_operation);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 83;
			field();
			State = 84;
			array_operator();
			State = 85;
			bool_array();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Array_operatorContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode IN() { return GetToken(RAQLParser.IN, 0); }
		public Array_operatorContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_array_operator; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IRAQLVisitor<TResult> typedVisitor = visitor as IRAQLVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitArray_operator(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Array_operatorContext array_operator() {
		Array_operatorContext _localctx = new Array_operatorContext(Context, State);
		EnterRule(_localctx, 12, RULE_array_operator);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 87;
			Match(IN);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class String_operationContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public FieldContext field() {
			return GetRuleContext<FieldContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public String_operatorContext string_operator() {
			return GetRuleContext<String_operatorContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public StringContext @string() {
			return GetRuleContext<StringContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public NullstringContext nullstring() {
			return GetRuleContext<NullstringContext>(0);
		}
		public String_operationContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_string_operation; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IRAQLVisitor<TResult> typedVisitor = visitor as IRAQLVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitString_operation(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public String_operationContext string_operation() {
		String_operationContext _localctx = new String_operationContext(Context, State);
		EnterRule(_localctx, 14, RULE_string_operation);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 89;
			field();
			State = 90;
			string_operator();
			State = 93;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case STRING:
				{
				State = 91;
				@string();
				}
				break;
			case NULL:
				{
				State = 92;
				nullstring();
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class String_operatorContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode BASE_OPERATOR() { return GetToken(RAQLParser.BASE_OPERATOR, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode STRING_OPERATOR() { return GetToken(RAQLParser.STRING_OPERATOR, 0); }
		public String_operatorContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_string_operator; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IRAQLVisitor<TResult> typedVisitor = visitor as IRAQLVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitString_operator(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public String_operatorContext string_operator() {
		String_operatorContext _localctx = new String_operatorContext(Context, State);
		EnterRule(_localctx, 16, RULE_string_operator);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 95;
			_la = TokenStream.LA(1);
			if ( !(_la==BASE_OPERATOR || _la==STRING_OPERATOR) ) {
			ErrorHandler.RecoverInline(this);
			}
			else {
				ErrorHandler.ReportMatch(this);
			    Consume();
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Number_operationContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public FieldContext field() {
			return GetRuleContext<FieldContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Number_operatorContext number_operator() {
			return GetRuleContext<Number_operatorContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public NumberContext number() {
			return GetRuleContext<NumberContext>(0);
		}
		public Number_operationContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_number_operation; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IRAQLVisitor<TResult> typedVisitor = visitor as IRAQLVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitNumber_operation(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Number_operationContext number_operation() {
		Number_operationContext _localctx = new Number_operationContext(Context, State);
		EnterRule(_localctx, 18, RULE_number_operation);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 97;
			field();
			State = 98;
			number_operator();
			State = 99;
			number();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Number_operatorContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode BASE_OPERATOR() { return GetToken(RAQLParser.BASE_OPERATOR, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode NUMBER_OPERATOR() { return GetToken(RAQLParser.NUMBER_OPERATOR, 0); }
		public Number_operatorContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_number_operator; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IRAQLVisitor<TResult> typedVisitor = visitor as IRAQLVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitNumber_operator(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Number_operatorContext number_operator() {
		Number_operatorContext _localctx = new Number_operatorContext(Context, State);
		EnterRule(_localctx, 20, RULE_number_operator);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 101;
			_la = TokenStream.LA(1);
			if ( !(_la==BASE_OPERATOR || _la==NUMBER_OPERATOR) ) {
			ErrorHandler.RecoverInline(this);
			}
			else {
				ErrorHandler.ReportMatch(this);
			    Consume();
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Bool_operationContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public FieldContext field() {
			return GetRuleContext<FieldContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Bool_operatorContext bool_operator() {
			return GetRuleContext<Bool_operatorContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public BoolContext @bool() {
			return GetRuleContext<BoolContext>(0);
		}
		public Bool_operationContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_bool_operation; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IRAQLVisitor<TResult> typedVisitor = visitor as IRAQLVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitBool_operation(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Bool_operationContext bool_operation() {
		Bool_operationContext _localctx = new Bool_operationContext(Context, State);
		EnterRule(_localctx, 22, RULE_bool_operation);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 103;
			field();
			State = 104;
			bool_operator();
			State = 105;
			@bool();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Bool_operatorContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode BASE_OPERATOR() { return GetToken(RAQLParser.BASE_OPERATOR, 0); }
		public Bool_operatorContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_bool_operator; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IRAQLVisitor<TResult> typedVisitor = visitor as IRAQLVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitBool_operator(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Bool_operatorContext bool_operator() {
		Bool_operatorContext _localctx = new Bool_operatorContext(Context, State);
		EnterRule(_localctx, 24, RULE_bool_operator);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 107;
			Match(BASE_OPERATOR);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class FieldContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] WORD() { return GetTokens(RAQLParser.WORD); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode WORD(int i) {
			return GetToken(RAQLParser.WORD, i);
		}
		public FieldContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_field; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IRAQLVisitor<TResult> typedVisitor = visitor as IRAQLVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitField(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public FieldContext field() {
		FieldContext _localctx = new FieldContext(Context, State);
		EnterRule(_localctx, 26, RULE_field);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 112;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==WORD) {
				{
				{
				State = 109;
				Match(WORD);
				}
				}
				State = 114;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class NullstringContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode NULL() { return GetToken(RAQLParser.NULL, 0); }
		public NullstringContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_nullstring; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IRAQLVisitor<TResult> typedVisitor = visitor as IRAQLVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitNullstring(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public NullstringContext nullstring() {
		NullstringContext _localctx = new NullstringContext(Context, State);
		EnterRule(_localctx, 28, RULE_nullstring);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 115;
			Match(NULL);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class StringContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode STRING() { return GetToken(RAQLParser.STRING, 0); }
		public StringContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_string; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IRAQLVisitor<TResult> typedVisitor = visitor as IRAQLVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitString(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public StringContext @string() {
		StringContext _localctx = new StringContext(Context, State);
		EnterRule(_localctx, 30, RULE_string);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 117;
			Match(STRING);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class String_arrayContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public StringContext[] @string() {
			return GetRuleContexts<StringContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public StringContext @string(int i) {
			return GetRuleContext<StringContext>(i);
		}
		public String_arrayContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_string_array; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IRAQLVisitor<TResult> typedVisitor = visitor as IRAQLVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitString_array(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public String_arrayContext string_array() {
		String_arrayContext _localctx = new String_arrayContext(Context, State);
		EnterRule(_localctx, 32, RULE_string_array);
		int _la;
		try {
			State = 132;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,8,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 119;
				Match(T__3);
				State = 120;
				@string();
				State = 125;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				while (_la==T__4) {
					{
					{
					State = 121;
					Match(T__4);
					State = 122;
					@string();
					}
					}
					State = 127;
					ErrorHandler.Sync(this);
					_la = TokenStream.LA(1);
				}
				State = 128;
				Match(T__5);
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 130;
				Match(T__3);
				State = 131;
				Match(T__5);
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class NumberContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode NUMBER() { return GetToken(RAQLParser.NUMBER, 0); }
		public NumberContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_number; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IRAQLVisitor<TResult> typedVisitor = visitor as IRAQLVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitNumber(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public NumberContext number() {
		NumberContext _localctx = new NumberContext(Context, State);
		EnterRule(_localctx, 34, RULE_number);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 134;
			Match(NUMBER);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Number_arrayContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public NumberContext[] number() {
			return GetRuleContexts<NumberContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public NumberContext number(int i) {
			return GetRuleContext<NumberContext>(i);
		}
		public Number_arrayContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_number_array; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IRAQLVisitor<TResult> typedVisitor = visitor as IRAQLVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitNumber_array(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Number_arrayContext number_array() {
		Number_arrayContext _localctx = new Number_arrayContext(Context, State);
		EnterRule(_localctx, 36, RULE_number_array);
		int _la;
		try {
			State = 149;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,10,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 136;
				Match(T__3);
				State = 137;
				number();
				State = 142;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				while (_la==T__4) {
					{
					{
					State = 138;
					Match(T__4);
					State = 139;
					number();
					}
					}
					State = 144;
					ErrorHandler.Sync(this);
					_la = TokenStream.LA(1);
				}
				State = 145;
				Match(T__5);
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 147;
				Match(T__3);
				State = 148;
				Match(T__5);
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class BoolContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode BOOLEAN() { return GetToken(RAQLParser.BOOLEAN, 0); }
		public BoolContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_bool; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IRAQLVisitor<TResult> typedVisitor = visitor as IRAQLVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitBool(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public BoolContext @bool() {
		BoolContext _localctx = new BoolContext(Context, State);
		EnterRule(_localctx, 38, RULE_bool);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 151;
			Match(BOOLEAN);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Bool_arrayContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public BoolContext[] @bool() {
			return GetRuleContexts<BoolContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public BoolContext @bool(int i) {
			return GetRuleContext<BoolContext>(i);
		}
		public Bool_arrayContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_bool_array; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IRAQLVisitor<TResult> typedVisitor = visitor as IRAQLVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitBool_array(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Bool_arrayContext bool_array() {
		Bool_arrayContext _localctx = new Bool_arrayContext(Context, State);
		EnterRule(_localctx, 40, RULE_bool_array);
		int _la;
		try {
			State = 166;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,12,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 153;
				Match(T__3);
				State = 154;
				@bool();
				State = 159;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				while (_la==T__4) {
					{
					{
					State = 155;
					Match(T__4);
					State = 156;
					@bool();
					}
					}
					State = 161;
					ErrorHandler.Sync(this);
					_la = TokenStream.LA(1);
				}
				State = 162;
				Match(T__5);
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 164;
				Match(T__3);
				State = 165;
				Match(T__5);
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public override bool Sempred(RuleContext _localctx, int ruleIndex, int predIndex) {
		switch (ruleIndex) {
		case 0: return clause_sempred((ClauseContext)_localctx, predIndex);
		}
		return true;
	}
	private bool clause_sempred(ClauseContext _localctx, int predIndex) {
		switch (predIndex) {
		case 0: return Precpred(Context, 2);
		}
		return true;
	}

	private static char[] _serializedATN = {
		'\x3', '\x608B', '\xA72A', '\x8133', '\xB9ED', '\x417C', '\x3BE7', '\x7786', 
		'\x5964', '\x3', '\x13', '\xAB', '\x4', '\x2', '\t', '\x2', '\x4', '\x3', 
		'\t', '\x3', '\x4', '\x4', '\t', '\x4', '\x4', '\x5', '\t', '\x5', '\x4', 
		'\x6', '\t', '\x6', '\x4', '\a', '\t', '\a', '\x4', '\b', '\t', '\b', 
		'\x4', '\t', '\t', '\t', '\x4', '\n', '\t', '\n', '\x4', '\v', '\t', '\v', 
		'\x4', '\f', '\t', '\f', '\x4', '\r', '\t', '\r', '\x4', '\xE', '\t', 
		'\xE', '\x4', '\xF', '\t', '\xF', '\x4', '\x10', '\t', '\x10', '\x4', 
		'\x11', '\t', '\x11', '\x4', '\x12', '\t', '\x12', '\x4', '\x13', '\t', 
		'\x13', '\x4', '\x14', '\t', '\x14', '\x4', '\x15', '\t', '\x15', '\x4', 
		'\x16', '\t', '\x16', '\x3', '\x2', '\x3', '\x2', '\x3', '\x2', '\x5', 
		'\x2', '\x30', '\n', '\x2', '\x3', '\x2', '\x3', '\x2', '\x5', '\x2', 
		'\x34', '\n', '\x2', '\x3', '\x2', '\x3', '\x2', '\x3', '\x2', '\x5', 
		'\x2', '\x39', '\n', '\x2', '\x3', '\x2', '\x3', '\x2', '\x3', '\x2', 
		'\x3', '\x2', '\a', '\x2', '?', '\n', '\x2', '\f', '\x2', '\xE', '\x2', 
		'\x42', '\v', '\x2', '\x3', '\x3', '\x3', '\x3', '\x3', '\x4', '\x3', 
		'\x4', '\x3', '\x4', '\x3', '\x4', '\x3', '\x4', '\x3', '\x4', '\x5', 
		'\x4', 'L', '\n', '\x4', '\x3', '\x5', '\x3', '\x5', '\x3', '\x5', '\x3', 
		'\x5', '\x3', '\x6', '\x3', '\x6', '\x3', '\x6', '\x3', '\x6', '\x3', 
		'\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', '\b', '\x3', '\b', 
		'\x3', '\t', '\x3', '\t', '\x3', '\t', '\x3', '\t', '\x5', '\t', '`', 
		'\n', '\t', '\x3', '\n', '\x3', '\n', '\x3', '\v', '\x3', '\v', '\x3', 
		'\v', '\x3', '\v', '\x3', '\f', '\x3', '\f', '\x3', '\r', '\x3', '\r', 
		'\x3', '\r', '\x3', '\r', '\x3', '\xE', '\x3', '\xE', '\x3', '\xF', '\a', 
		'\xF', 'q', '\n', '\xF', '\f', '\xF', '\xE', '\xF', 't', '\v', '\xF', 
		'\x3', '\x10', '\x3', '\x10', '\x3', '\x11', '\x3', '\x11', '\x3', '\x12', 
		'\x3', '\x12', '\x3', '\x12', '\x3', '\x12', '\a', '\x12', '~', '\n', 
		'\x12', '\f', '\x12', '\xE', '\x12', '\x81', '\v', '\x12', '\x3', '\x12', 
		'\x3', '\x12', '\x3', '\x12', '\x3', '\x12', '\x5', '\x12', '\x87', '\n', 
		'\x12', '\x3', '\x13', '\x3', '\x13', '\x3', '\x14', '\x3', '\x14', '\x3', 
		'\x14', '\x3', '\x14', '\a', '\x14', '\x8F', '\n', '\x14', '\f', '\x14', 
		'\xE', '\x14', '\x92', '\v', '\x14', '\x3', '\x14', '\x3', '\x14', '\x3', 
		'\x14', '\x3', '\x14', '\x5', '\x14', '\x98', '\n', '\x14', '\x3', '\x15', 
		'\x3', '\x15', '\x3', '\x16', '\x3', '\x16', '\x3', '\x16', '\x3', '\x16', 
		'\a', '\x16', '\xA0', '\n', '\x16', '\f', '\x16', '\xE', '\x16', '\xA3', 
		'\v', '\x16', '\x3', '\x16', '\x3', '\x16', '\x3', '\x16', '\x3', '\x16', 
		'\x5', '\x16', '\xA9', '\n', '\x16', '\x3', '\x16', '\x2', '\x3', '\x2', 
		'\x17', '\x2', '\x4', '\x6', '\b', '\n', '\f', '\xE', '\x10', '\x12', 
		'\x14', '\x16', '\x18', '\x1A', '\x1C', '\x1E', ' ', '\"', '$', '&', '(', 
		'*', '\x2', '\x4', '\x3', '\x2', '\n', '\v', '\x4', '\x2', '\n', '\n', 
		'\f', '\f', '\x2', '\xA7', '\x2', '\x38', '\x3', '\x2', '\x2', '\x2', 
		'\x4', '\x43', '\x3', '\x2', '\x2', '\x2', '\x6', 'K', '\x3', '\x2', '\x2', 
		'\x2', '\b', 'M', '\x3', '\x2', '\x2', '\x2', '\n', 'Q', '\x3', '\x2', 
		'\x2', '\x2', '\f', 'U', '\x3', '\x2', '\x2', '\x2', '\xE', 'Y', '\x3', 
		'\x2', '\x2', '\x2', '\x10', '[', '\x3', '\x2', '\x2', '\x2', '\x12', 
		'\x61', '\x3', '\x2', '\x2', '\x2', '\x14', '\x63', '\x3', '\x2', '\x2', 
		'\x2', '\x16', 'g', '\x3', '\x2', '\x2', '\x2', '\x18', 'i', '\x3', '\x2', 
		'\x2', '\x2', '\x1A', 'm', '\x3', '\x2', '\x2', '\x2', '\x1C', 'r', '\x3', 
		'\x2', '\x2', '\x2', '\x1E', 'u', '\x3', '\x2', '\x2', '\x2', ' ', 'w', 
		'\x3', '\x2', '\x2', '\x2', '\"', '\x86', '\x3', '\x2', '\x2', '\x2', 
		'$', '\x88', '\x3', '\x2', '\x2', '\x2', '&', '\x97', '\x3', '\x2', '\x2', 
		'\x2', '(', '\x99', '\x3', '\x2', '\x2', '\x2', '*', '\xA8', '\x3', '\x2', 
		'\x2', '\x2', ',', '\x39', '\b', '\x2', '\x1', '\x2', '-', '/', '\a', 
		'\x3', '\x2', '\x2', '.', '\x30', '\a', '\x4', '\x2', '\x2', '/', '.', 
		'\x3', '\x2', '\x2', '\x2', '/', '\x30', '\x3', '\x2', '\x2', '\x2', '\x30', 
		'\x31', '\x3', '\x2', '\x2', '\x2', '\x31', '\x33', '\x5', '\x2', '\x2', 
		'\x2', '\x32', '\x34', '\a', '\x4', '\x2', '\x2', '\x33', '\x32', '\x3', 
		'\x2', '\x2', '\x2', '\x33', '\x34', '\x3', '\x2', '\x2', '\x2', '\x34', 
		'\x35', '\x3', '\x2', '\x2', '\x2', '\x35', '\x36', '\a', '\x5', '\x2', 
		'\x2', '\x36', '\x39', '\x3', '\x2', '\x2', '\x2', '\x37', '\x39', '\x5', 
		'\x6', '\x4', '\x2', '\x38', ',', '\x3', '\x2', '\x2', '\x2', '\x38', 
		'-', '\x3', '\x2', '\x2', '\x2', '\x38', '\x37', '\x3', '\x2', '\x2', 
		'\x2', '\x39', '@', '\x3', '\x2', '\x2', '\x2', ':', ';', '\f', '\x4', 
		'\x2', '\x2', ';', '<', '\x5', '\x4', '\x3', '\x2', '<', '=', '\x5', '\x2', 
		'\x2', '\x5', '=', '?', '\x3', '\x2', '\x2', '\x2', '>', ':', '\x3', '\x2', 
		'\x2', '\x2', '?', '\x42', '\x3', '\x2', '\x2', '\x2', '@', '>', '\x3', 
		'\x2', '\x2', '\x2', '@', '\x41', '\x3', '\x2', '\x2', '\x2', '\x41', 
		'\x3', '\x3', '\x2', '\x2', '\x2', '\x42', '@', '\x3', '\x2', '\x2', '\x2', 
		'\x43', '\x44', '\a', '\r', '\x2', '\x2', '\x44', '\x5', '\x3', '\x2', 
		'\x2', '\x2', '\x45', 'L', '\x5', '\f', '\a', '\x2', '\x46', 'L', '\x5', 
		'\n', '\x6', '\x2', 'G', 'L', '\x5', '\b', '\x5', '\x2', 'H', 'L', '\x5', 
		'\x18', '\r', '\x2', 'I', 'L', '\x5', '\x14', '\v', '\x2', 'J', 'L', '\x5', 
		'\x10', '\t', '\x2', 'K', '\x45', '\x3', '\x2', '\x2', '\x2', 'K', '\x46', 
		'\x3', '\x2', '\x2', '\x2', 'K', 'G', '\x3', '\x2', '\x2', '\x2', 'K', 
		'H', '\x3', '\x2', '\x2', '\x2', 'K', 'I', '\x3', '\x2', '\x2', '\x2', 
		'K', 'J', '\x3', '\x2', '\x2', '\x2', 'L', '\a', '\x3', '\x2', '\x2', 
		'\x2', 'M', 'N', '\x5', '\x1C', '\xF', '\x2', 'N', 'O', '\x5', '\xE', 
		'\b', '\x2', 'O', 'P', '\x5', '\"', '\x12', '\x2', 'P', '\t', '\x3', '\x2', 
		'\x2', '\x2', 'Q', 'R', '\x5', '\x1C', '\xF', '\x2', 'R', 'S', '\x5', 
		'\xE', '\b', '\x2', 'S', 'T', '\x5', '&', '\x14', '\x2', 'T', '\v', '\x3', 
		'\x2', '\x2', '\x2', 'U', 'V', '\x5', '\x1C', '\xF', '\x2', 'V', 'W', 
		'\x5', '\xE', '\b', '\x2', 'W', 'X', '\x5', '*', '\x16', '\x2', 'X', '\r', 
		'\x3', '\x2', '\x2', '\x2', 'Y', 'Z', '\a', '\t', '\x2', '\x2', 'Z', '\xF', 
		'\x3', '\x2', '\x2', '\x2', '[', '\\', '\x5', '\x1C', '\xF', '\x2', '\\', 
		'_', '\x5', '\x12', '\n', '\x2', ']', '`', '\x5', ' ', '\x11', '\x2', 
		'^', '`', '\x5', '\x1E', '\x10', '\x2', '_', ']', '\x3', '\x2', '\x2', 
		'\x2', '_', '^', '\x3', '\x2', '\x2', '\x2', '`', '\x11', '\x3', '\x2', 
		'\x2', '\x2', '\x61', '\x62', '\t', '\x2', '\x2', '\x2', '\x62', '\x13', 
		'\x3', '\x2', '\x2', '\x2', '\x63', '\x64', '\x5', '\x1C', '\xF', '\x2', 
		'\x64', '\x65', '\x5', '\x16', '\f', '\x2', '\x65', '\x66', '\x5', '$', 
		'\x13', '\x2', '\x66', '\x15', '\x3', '\x2', '\x2', '\x2', 'g', 'h', '\t', 
		'\x3', '\x2', '\x2', 'h', '\x17', '\x3', '\x2', '\x2', '\x2', 'i', 'j', 
		'\x5', '\x1C', '\xF', '\x2', 'j', 'k', '\x5', '\x1A', '\xE', '\x2', 'k', 
		'l', '\x5', '(', '\x15', '\x2', 'l', '\x19', '\x3', '\x2', '\x2', '\x2', 
		'm', 'n', '\a', '\n', '\x2', '\x2', 'n', '\x1B', '\x3', '\x2', '\x2', 
		'\x2', 'o', 'q', '\a', '\xF', '\x2', '\x2', 'p', 'o', '\x3', '\x2', '\x2', 
		'\x2', 'q', 't', '\x3', '\x2', '\x2', '\x2', 'r', 'p', '\x3', '\x2', '\x2', 
		'\x2', 'r', 's', '\x3', '\x2', '\x2', '\x2', 's', '\x1D', '\x3', '\x2', 
		'\x2', '\x2', 't', 'r', '\x3', '\x2', '\x2', '\x2', 'u', 'v', '\a', '\x12', 
		'\x2', '\x2', 'v', '\x1F', '\x3', '\x2', '\x2', '\x2', 'w', 'x', '\a', 
		'\x10', '\x2', '\x2', 'x', '!', '\x3', '\x2', '\x2', '\x2', 'y', 'z', 
		'\a', '\x6', '\x2', '\x2', 'z', '\x7F', '\x5', ' ', '\x11', '\x2', '{', 
		'|', '\a', '\a', '\x2', '\x2', '|', '~', '\x5', ' ', '\x11', '\x2', '}', 
		'{', '\x3', '\x2', '\x2', '\x2', '~', '\x81', '\x3', '\x2', '\x2', '\x2', 
		'\x7F', '}', '\x3', '\x2', '\x2', '\x2', '\x7F', '\x80', '\x3', '\x2', 
		'\x2', '\x2', '\x80', '\x82', '\x3', '\x2', '\x2', '\x2', '\x81', '\x7F', 
		'\x3', '\x2', '\x2', '\x2', '\x82', '\x83', '\a', '\b', '\x2', '\x2', 
		'\x83', '\x87', '\x3', '\x2', '\x2', '\x2', '\x84', '\x85', '\a', '\x6', 
		'\x2', '\x2', '\x85', '\x87', '\a', '\b', '\x2', '\x2', '\x86', 'y', '\x3', 
		'\x2', '\x2', '\x2', '\x86', '\x84', '\x3', '\x2', '\x2', '\x2', '\x87', 
		'#', '\x3', '\x2', '\x2', '\x2', '\x88', '\x89', '\a', '\xE', '\x2', '\x2', 
		'\x89', '%', '\x3', '\x2', '\x2', '\x2', '\x8A', '\x8B', '\a', '\x6', 
		'\x2', '\x2', '\x8B', '\x90', '\x5', '$', '\x13', '\x2', '\x8C', '\x8D', 
		'\a', '\a', '\x2', '\x2', '\x8D', '\x8F', '\x5', '$', '\x13', '\x2', '\x8E', 
		'\x8C', '\x3', '\x2', '\x2', '\x2', '\x8F', '\x92', '\x3', '\x2', '\x2', 
		'\x2', '\x90', '\x8E', '\x3', '\x2', '\x2', '\x2', '\x90', '\x91', '\x3', 
		'\x2', '\x2', '\x2', '\x91', '\x93', '\x3', '\x2', '\x2', '\x2', '\x92', 
		'\x90', '\x3', '\x2', '\x2', '\x2', '\x93', '\x94', '\a', '\b', '\x2', 
		'\x2', '\x94', '\x98', '\x3', '\x2', '\x2', '\x2', '\x95', '\x96', '\a', 
		'\x6', '\x2', '\x2', '\x96', '\x98', '\a', '\b', '\x2', '\x2', '\x97', 
		'\x8A', '\x3', '\x2', '\x2', '\x2', '\x97', '\x95', '\x3', '\x2', '\x2', 
		'\x2', '\x98', '\'', '\x3', '\x2', '\x2', '\x2', '\x99', '\x9A', '\a', 
		'\x11', '\x2', '\x2', '\x9A', ')', '\x3', '\x2', '\x2', '\x2', '\x9B', 
		'\x9C', '\a', '\x6', '\x2', '\x2', '\x9C', '\xA1', '\x5', '(', '\x15', 
		'\x2', '\x9D', '\x9E', '\a', '\a', '\x2', '\x2', '\x9E', '\xA0', '\x5', 
		'(', '\x15', '\x2', '\x9F', '\x9D', '\x3', '\x2', '\x2', '\x2', '\xA0', 
		'\xA3', '\x3', '\x2', '\x2', '\x2', '\xA1', '\x9F', '\x3', '\x2', '\x2', 
		'\x2', '\xA1', '\xA2', '\x3', '\x2', '\x2', '\x2', '\xA2', '\xA4', '\x3', 
		'\x2', '\x2', '\x2', '\xA3', '\xA1', '\x3', '\x2', '\x2', '\x2', '\xA4', 
		'\xA5', '\a', '\b', '\x2', '\x2', '\xA5', '\xA9', '\x3', '\x2', '\x2', 
		'\x2', '\xA6', '\xA7', '\a', '\x6', '\x2', '\x2', '\xA7', '\xA9', '\a', 
		'\b', '\x2', '\x2', '\xA8', '\x9B', '\x3', '\x2', '\x2', '\x2', '\xA8', 
		'\xA6', '\x3', '\x2', '\x2', '\x2', '\xA9', '+', '\x3', '\x2', '\x2', 
		'\x2', '\xF', '/', '\x33', '\x38', '@', 'K', '_', 'r', '\x7F', '\x86', 
		'\x90', '\x97', '\xA1', '\xA8',
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
