//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.9.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from /Users/rchdeveloper/Documents/GitHub/api-query-language/RAQL-dotnet/RAQL-dotnet/RAQL.g4 by ANTLR 4.9.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="RAQLParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.9.2")]
[System.CLSCompliant(false)]
public interface IRAQLVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="RAQLParser.clause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitClause([NotNull] RAQLParser.ClauseContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="RAQLParser.conjunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConjunction([NotNull] RAQLParser.ConjunctionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="RAQLParser.operation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOperation([NotNull] RAQLParser.OperationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="RAQLParser.string_array_operation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitString_array_operation([NotNull] RAQLParser.String_array_operationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="RAQLParser.number_array_operation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNumber_array_operation([NotNull] RAQLParser.Number_array_operationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="RAQLParser.bool_array_operation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBool_array_operation([NotNull] RAQLParser.Bool_array_operationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="RAQLParser.array_operator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArray_operator([NotNull] RAQLParser.Array_operatorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="RAQLParser.string_operation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitString_operation([NotNull] RAQLParser.String_operationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="RAQLParser.string_operator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitString_operator([NotNull] RAQLParser.String_operatorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="RAQLParser.number_operation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNumber_operation([NotNull] RAQLParser.Number_operationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="RAQLParser.number_operator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNumber_operator([NotNull] RAQLParser.Number_operatorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="RAQLParser.bool_operation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBool_operation([NotNull] RAQLParser.Bool_operationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="RAQLParser.bool_operator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBool_operator([NotNull] RAQLParser.Bool_operatorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="RAQLParser.field"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitField([NotNull] RAQLParser.FieldContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="RAQLParser.nullstring"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNullstring([NotNull] RAQLParser.NullstringContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="RAQLParser.string"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitString([NotNull] RAQLParser.StringContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="RAQLParser.string_array"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitString_array([NotNull] RAQLParser.String_arrayContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="RAQLParser.number"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNumber([NotNull] RAQLParser.NumberContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="RAQLParser.number_array"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNumber_array([NotNull] RAQLParser.Number_arrayContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="RAQLParser.bool"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBool([NotNull] RAQLParser.BoolContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="RAQLParser.bool_array"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBool_array([NotNull] RAQLParser.Bool_arrayContext context);
}
