//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.9.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from /Users/rchdeveloper/Documents/GitHub/api-query-language/RAQL-dotnet/RAQL-dotnet/RAQL.g4 by ANTLR 4.9.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="RAQLParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.9.2")]
[System.CLSCompliant(false)]
public interface IRAQLListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="RAQLParser.clause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterClause([NotNull] RAQLParser.ClauseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RAQLParser.clause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitClause([NotNull] RAQLParser.ClauseContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RAQLParser.conjunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterConjunction([NotNull] RAQLParser.ConjunctionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RAQLParser.conjunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitConjunction([NotNull] RAQLParser.ConjunctionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RAQLParser.operation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOperation([NotNull] RAQLParser.OperationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RAQLParser.operation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOperation([NotNull] RAQLParser.OperationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RAQLParser.string_array_operation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterString_array_operation([NotNull] RAQLParser.String_array_operationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RAQLParser.string_array_operation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitString_array_operation([NotNull] RAQLParser.String_array_operationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RAQLParser.number_array_operation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNumber_array_operation([NotNull] RAQLParser.Number_array_operationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RAQLParser.number_array_operation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNumber_array_operation([NotNull] RAQLParser.Number_array_operationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RAQLParser.bool_array_operation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBool_array_operation([NotNull] RAQLParser.Bool_array_operationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RAQLParser.bool_array_operation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBool_array_operation([NotNull] RAQLParser.Bool_array_operationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RAQLParser.array_operator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArray_operator([NotNull] RAQLParser.Array_operatorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RAQLParser.array_operator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArray_operator([NotNull] RAQLParser.Array_operatorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RAQLParser.string_operation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterString_operation([NotNull] RAQLParser.String_operationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RAQLParser.string_operation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitString_operation([NotNull] RAQLParser.String_operationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RAQLParser.string_operator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterString_operator([NotNull] RAQLParser.String_operatorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RAQLParser.string_operator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitString_operator([NotNull] RAQLParser.String_operatorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RAQLParser.number_operation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNumber_operation([NotNull] RAQLParser.Number_operationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RAQLParser.number_operation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNumber_operation([NotNull] RAQLParser.Number_operationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RAQLParser.number_operator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNumber_operator([NotNull] RAQLParser.Number_operatorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RAQLParser.number_operator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNumber_operator([NotNull] RAQLParser.Number_operatorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RAQLParser.bool_operation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBool_operation([NotNull] RAQLParser.Bool_operationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RAQLParser.bool_operation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBool_operation([NotNull] RAQLParser.Bool_operationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RAQLParser.bool_operator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBool_operator([NotNull] RAQLParser.Bool_operatorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RAQLParser.bool_operator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBool_operator([NotNull] RAQLParser.Bool_operatorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RAQLParser.field"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterField([NotNull] RAQLParser.FieldContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RAQLParser.field"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitField([NotNull] RAQLParser.FieldContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RAQLParser.nullstring"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNullstring([NotNull] RAQLParser.NullstringContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RAQLParser.nullstring"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNullstring([NotNull] RAQLParser.NullstringContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RAQLParser.string"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterString([NotNull] RAQLParser.StringContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RAQLParser.string"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitString([NotNull] RAQLParser.StringContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RAQLParser.string_array"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterString_array([NotNull] RAQLParser.String_arrayContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RAQLParser.string_array"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitString_array([NotNull] RAQLParser.String_arrayContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RAQLParser.number"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNumber([NotNull] RAQLParser.NumberContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RAQLParser.number"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNumber([NotNull] RAQLParser.NumberContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RAQLParser.number_array"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNumber_array([NotNull] RAQLParser.Number_arrayContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RAQLParser.number_array"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNumber_array([NotNull] RAQLParser.Number_arrayContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RAQLParser.bool"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBool([NotNull] RAQLParser.BoolContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RAQLParser.bool"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBool([NotNull] RAQLParser.BoolContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RAQLParser.bool_array"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBool_array([NotNull] RAQLParser.Bool_arrayContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RAQLParser.bool_array"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBool_array([NotNull] RAQLParser.Bool_arrayContext context);
}
