//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.9.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from /Users/rchdeveloper/Documents/GitHub/api-query-language/RAQL-dotnet/RAQL-dotnet/RAQL.g4 by ANTLR 4.9.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IRAQLListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.9.2")]
[System.Diagnostics.DebuggerNonUserCode]
[System.CLSCompliant(false)]
public partial class RAQLBaseListener : IRAQLListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="RAQLParser.clause"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterClause([NotNull] RAQLParser.ClauseContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RAQLParser.clause"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitClause([NotNull] RAQLParser.ClauseContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RAQLParser.conjunction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterConjunction([NotNull] RAQLParser.ConjunctionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RAQLParser.conjunction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitConjunction([NotNull] RAQLParser.ConjunctionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RAQLParser.operation"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOperation([NotNull] RAQLParser.OperationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RAQLParser.operation"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOperation([NotNull] RAQLParser.OperationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RAQLParser.string_array_operation"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterString_array_operation([NotNull] RAQLParser.String_array_operationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RAQLParser.string_array_operation"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitString_array_operation([NotNull] RAQLParser.String_array_operationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RAQLParser.number_array_operation"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNumber_array_operation([NotNull] RAQLParser.Number_array_operationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RAQLParser.number_array_operation"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNumber_array_operation([NotNull] RAQLParser.Number_array_operationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RAQLParser.bool_array_operation"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBool_array_operation([NotNull] RAQLParser.Bool_array_operationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RAQLParser.bool_array_operation"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBool_array_operation([NotNull] RAQLParser.Bool_array_operationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RAQLParser.array_operator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArray_operator([NotNull] RAQLParser.Array_operatorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RAQLParser.array_operator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArray_operator([NotNull] RAQLParser.Array_operatorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RAQLParser.string_operation"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterString_operation([NotNull] RAQLParser.String_operationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RAQLParser.string_operation"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitString_operation([NotNull] RAQLParser.String_operationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RAQLParser.string_operator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterString_operator([NotNull] RAQLParser.String_operatorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RAQLParser.string_operator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitString_operator([NotNull] RAQLParser.String_operatorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RAQLParser.number_operation"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNumber_operation([NotNull] RAQLParser.Number_operationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RAQLParser.number_operation"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNumber_operation([NotNull] RAQLParser.Number_operationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RAQLParser.number_operator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNumber_operator([NotNull] RAQLParser.Number_operatorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RAQLParser.number_operator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNumber_operator([NotNull] RAQLParser.Number_operatorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RAQLParser.bool_operation"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBool_operation([NotNull] RAQLParser.Bool_operationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RAQLParser.bool_operation"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBool_operation([NotNull] RAQLParser.Bool_operationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RAQLParser.bool_operator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBool_operator([NotNull] RAQLParser.Bool_operatorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RAQLParser.bool_operator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBool_operator([NotNull] RAQLParser.Bool_operatorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RAQLParser.field"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterField([NotNull] RAQLParser.FieldContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RAQLParser.field"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitField([NotNull] RAQLParser.FieldContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RAQLParser.nullstring"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNullstring([NotNull] RAQLParser.NullstringContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RAQLParser.nullstring"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNullstring([NotNull] RAQLParser.NullstringContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RAQLParser.string"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterString([NotNull] RAQLParser.StringContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RAQLParser.string"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitString([NotNull] RAQLParser.StringContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RAQLParser.string_array"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterString_array([NotNull] RAQLParser.String_arrayContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RAQLParser.string_array"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitString_array([NotNull] RAQLParser.String_arrayContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RAQLParser.number"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNumber([NotNull] RAQLParser.NumberContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RAQLParser.number"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNumber([NotNull] RAQLParser.NumberContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RAQLParser.number_array"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNumber_array([NotNull] RAQLParser.Number_arrayContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RAQLParser.number_array"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNumber_array([NotNull] RAQLParser.Number_arrayContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RAQLParser.bool"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBool([NotNull] RAQLParser.BoolContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RAQLParser.bool"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBool([NotNull] RAQLParser.BoolContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RAQLParser.bool_array"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBool_array([NotNull] RAQLParser.Bool_arrayContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RAQLParser.bool_array"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBool_array([NotNull] RAQLParser.Bool_arrayContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
