//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.9.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from /Users/rchdeveloper/Documents/GitHub/api-query-language/apl-dotnet/apl-dotnet/APLGrammar.g4 by ANTLR 4.9.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IAPLGrammarListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.9.2")]
[System.Diagnostics.DebuggerNonUserCode]
[System.CLSCompliant(false)]
public partial class APLGrammarBaseListener : IAPLGrammarListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="APLGrammarParser.clause"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterClause([NotNull] APLGrammarParser.ClauseContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="APLGrammarParser.clause"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitClause([NotNull] APLGrammarParser.ClauseContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="APLGrammarParser.conjunction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterConjunction([NotNull] APLGrammarParser.ConjunctionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="APLGrammarParser.conjunction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitConjunction([NotNull] APLGrammarParser.ConjunctionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="APLGrammarParser.operation"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOperation([NotNull] APLGrammarParser.OperationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="APLGrammarParser.operation"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOperation([NotNull] APLGrammarParser.OperationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="APLGrammarParser.string_array_operation"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterString_array_operation([NotNull] APLGrammarParser.String_array_operationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="APLGrammarParser.string_array_operation"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitString_array_operation([NotNull] APLGrammarParser.String_array_operationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="APLGrammarParser.number_array_operation"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNumber_array_operation([NotNull] APLGrammarParser.Number_array_operationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="APLGrammarParser.number_array_operation"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNumber_array_operation([NotNull] APLGrammarParser.Number_array_operationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="APLGrammarParser.bool_array_operation"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBool_array_operation([NotNull] APLGrammarParser.Bool_array_operationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="APLGrammarParser.bool_array_operation"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBool_array_operation([NotNull] APLGrammarParser.Bool_array_operationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="APLGrammarParser.array_operator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArray_operator([NotNull] APLGrammarParser.Array_operatorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="APLGrammarParser.array_operator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArray_operator([NotNull] APLGrammarParser.Array_operatorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="APLGrammarParser.string_operation"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterString_operation([NotNull] APLGrammarParser.String_operationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="APLGrammarParser.string_operation"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitString_operation([NotNull] APLGrammarParser.String_operationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="APLGrammarParser.string_operator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterString_operator([NotNull] APLGrammarParser.String_operatorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="APLGrammarParser.string_operator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitString_operator([NotNull] APLGrammarParser.String_operatorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="APLGrammarParser.number_operation"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNumber_operation([NotNull] APLGrammarParser.Number_operationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="APLGrammarParser.number_operation"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNumber_operation([NotNull] APLGrammarParser.Number_operationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="APLGrammarParser.number_operator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNumber_operator([NotNull] APLGrammarParser.Number_operatorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="APLGrammarParser.number_operator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNumber_operator([NotNull] APLGrammarParser.Number_operatorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="APLGrammarParser.bool_operation"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBool_operation([NotNull] APLGrammarParser.Bool_operationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="APLGrammarParser.bool_operation"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBool_operation([NotNull] APLGrammarParser.Bool_operationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="APLGrammarParser.bool_operator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBool_operator([NotNull] APLGrammarParser.Bool_operatorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="APLGrammarParser.bool_operator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBool_operator([NotNull] APLGrammarParser.Bool_operatorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="APLGrammarParser.field"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterField([NotNull] APLGrammarParser.FieldContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="APLGrammarParser.field"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitField([NotNull] APLGrammarParser.FieldContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="APLGrammarParser.nullstring"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNullstring([NotNull] APLGrammarParser.NullstringContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="APLGrammarParser.nullstring"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNullstring([NotNull] APLGrammarParser.NullstringContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="APLGrammarParser.string"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterString([NotNull] APLGrammarParser.StringContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="APLGrammarParser.string"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitString([NotNull] APLGrammarParser.StringContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="APLGrammarParser.string_array"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterString_array([NotNull] APLGrammarParser.String_arrayContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="APLGrammarParser.string_array"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitString_array([NotNull] APLGrammarParser.String_arrayContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="APLGrammarParser.number"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNumber([NotNull] APLGrammarParser.NumberContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="APLGrammarParser.number"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNumber([NotNull] APLGrammarParser.NumberContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="APLGrammarParser.number_array"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNumber_array([NotNull] APLGrammarParser.Number_arrayContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="APLGrammarParser.number_array"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNumber_array([NotNull] APLGrammarParser.Number_arrayContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="APLGrammarParser.bool"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBool([NotNull] APLGrammarParser.BoolContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="APLGrammarParser.bool"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBool([NotNull] APLGrammarParser.BoolContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="APLGrammarParser.bool_array"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBool_array([NotNull] APLGrammarParser.Bool_arrayContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="APLGrammarParser.bool_array"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBool_array([NotNull] APLGrammarParser.Bool_arrayContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
