//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.9.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from /Users/rchdeveloper/Documents/GitHub/api-query-language/apl-dotnet/apl-dotnet/APLGrammar.g4 by ANTLR 4.9.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="APLGrammarParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.9.2")]
[System.CLSCompliant(false)]
public interface IAPLGrammarListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="APLGrammarParser.clause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterClause([NotNull] APLGrammarParser.ClauseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="APLGrammarParser.clause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitClause([NotNull] APLGrammarParser.ClauseContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="APLGrammarParser.conjunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterConjunction([NotNull] APLGrammarParser.ConjunctionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="APLGrammarParser.conjunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitConjunction([NotNull] APLGrammarParser.ConjunctionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="APLGrammarParser.operation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOperation([NotNull] APLGrammarParser.OperationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="APLGrammarParser.operation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOperation([NotNull] APLGrammarParser.OperationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="APLGrammarParser.string_array_operation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterString_array_operation([NotNull] APLGrammarParser.String_array_operationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="APLGrammarParser.string_array_operation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitString_array_operation([NotNull] APLGrammarParser.String_array_operationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="APLGrammarParser.number_array_operation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNumber_array_operation([NotNull] APLGrammarParser.Number_array_operationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="APLGrammarParser.number_array_operation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNumber_array_operation([NotNull] APLGrammarParser.Number_array_operationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="APLGrammarParser.bool_array_operation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBool_array_operation([NotNull] APLGrammarParser.Bool_array_operationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="APLGrammarParser.bool_array_operation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBool_array_operation([NotNull] APLGrammarParser.Bool_array_operationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="APLGrammarParser.array_operator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArray_operator([NotNull] APLGrammarParser.Array_operatorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="APLGrammarParser.array_operator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArray_operator([NotNull] APLGrammarParser.Array_operatorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="APLGrammarParser.string_operation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterString_operation([NotNull] APLGrammarParser.String_operationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="APLGrammarParser.string_operation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitString_operation([NotNull] APLGrammarParser.String_operationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="APLGrammarParser.string_operator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterString_operator([NotNull] APLGrammarParser.String_operatorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="APLGrammarParser.string_operator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitString_operator([NotNull] APLGrammarParser.String_operatorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="APLGrammarParser.number_operation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNumber_operation([NotNull] APLGrammarParser.Number_operationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="APLGrammarParser.number_operation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNumber_operation([NotNull] APLGrammarParser.Number_operationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="APLGrammarParser.number_operator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNumber_operator([NotNull] APLGrammarParser.Number_operatorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="APLGrammarParser.number_operator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNumber_operator([NotNull] APLGrammarParser.Number_operatorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="APLGrammarParser.bool_operation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBool_operation([NotNull] APLGrammarParser.Bool_operationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="APLGrammarParser.bool_operation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBool_operation([NotNull] APLGrammarParser.Bool_operationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="APLGrammarParser.bool_operator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBool_operator([NotNull] APLGrammarParser.Bool_operatorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="APLGrammarParser.bool_operator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBool_operator([NotNull] APLGrammarParser.Bool_operatorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="APLGrammarParser.field"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterField([NotNull] APLGrammarParser.FieldContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="APLGrammarParser.field"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitField([NotNull] APLGrammarParser.FieldContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="APLGrammarParser.nullstring"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNullstring([NotNull] APLGrammarParser.NullstringContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="APLGrammarParser.nullstring"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNullstring([NotNull] APLGrammarParser.NullstringContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="APLGrammarParser.string"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterString([NotNull] APLGrammarParser.StringContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="APLGrammarParser.string"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitString([NotNull] APLGrammarParser.StringContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="APLGrammarParser.string_array"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterString_array([NotNull] APLGrammarParser.String_arrayContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="APLGrammarParser.string_array"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitString_array([NotNull] APLGrammarParser.String_arrayContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="APLGrammarParser.number"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNumber([NotNull] APLGrammarParser.NumberContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="APLGrammarParser.number"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNumber([NotNull] APLGrammarParser.NumberContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="APLGrammarParser.number_array"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNumber_array([NotNull] APLGrammarParser.Number_arrayContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="APLGrammarParser.number_array"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNumber_array([NotNull] APLGrammarParser.Number_arrayContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="APLGrammarParser.bool"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBool([NotNull] APLGrammarParser.BoolContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="APLGrammarParser.bool"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBool([NotNull] APLGrammarParser.BoolContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="APLGrammarParser.bool_array"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBool_array([NotNull] APLGrammarParser.Bool_arrayContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="APLGrammarParser.bool_array"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBool_array([NotNull] APLGrammarParser.Bool_arrayContext context);
}
