//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.9.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from /Users/rchdeveloper/Documents/GitHub/api-query-language/apl-dotnet/apl-dotnet/APLGrammar.g4 by ANTLR 4.9.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="APLGrammarParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.9.2")]
[System.CLSCompliant(false)]
public interface IAPLGrammarVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="APLGrammarParser.clause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitClause([NotNull] APLGrammarParser.ClauseContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="APLGrammarParser.conjunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConjunction([NotNull] APLGrammarParser.ConjunctionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="APLGrammarParser.operation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOperation([NotNull] APLGrammarParser.OperationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="APLGrammarParser.string_array_operation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitString_array_operation([NotNull] APLGrammarParser.String_array_operationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="APLGrammarParser.number_array_operation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNumber_array_operation([NotNull] APLGrammarParser.Number_array_operationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="APLGrammarParser.bool_array_operation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBool_array_operation([NotNull] APLGrammarParser.Bool_array_operationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="APLGrammarParser.array_operator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArray_operator([NotNull] APLGrammarParser.Array_operatorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="APLGrammarParser.string_operation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitString_operation([NotNull] APLGrammarParser.String_operationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="APLGrammarParser.string_operator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitString_operator([NotNull] APLGrammarParser.String_operatorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="APLGrammarParser.number_operation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNumber_operation([NotNull] APLGrammarParser.Number_operationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="APLGrammarParser.number_operator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNumber_operator([NotNull] APLGrammarParser.Number_operatorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="APLGrammarParser.bool_operation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBool_operation([NotNull] APLGrammarParser.Bool_operationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="APLGrammarParser.bool_operator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBool_operator([NotNull] APLGrammarParser.Bool_operatorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="APLGrammarParser.field"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitField([NotNull] APLGrammarParser.FieldContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="APLGrammarParser.nullstring"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNullstring([NotNull] APLGrammarParser.NullstringContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="APLGrammarParser.string"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitString([NotNull] APLGrammarParser.StringContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="APLGrammarParser.string_array"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitString_array([NotNull] APLGrammarParser.String_arrayContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="APLGrammarParser.number"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNumber([NotNull] APLGrammarParser.NumberContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="APLGrammarParser.number_array"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNumber_array([NotNull] APLGrammarParser.Number_arrayContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="APLGrammarParser.bool"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBool([NotNull] APLGrammarParser.BoolContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="APLGrammarParser.bool_array"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBool_array([NotNull] APLGrammarParser.Bool_arrayContext context);
}
